"""Add SearchFilter and UserSearchFilters tables

Revision ID: c60cc46d9379
Revises: 760ac387b1f0
Create Date: 2025-09-14 23:02:56.358138

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlmodel

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c60cc46d9379"
down_revision: Union[str, Sequence[str], None] = "760ac387b1f0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "searchfilter",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filter_name", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("city_id", sa.Integer(), nullable=False),
        sa.Column("region_id", sa.Integer(), nullable=False),
        sa.Column("currency", sa.Enum("USD", "UAH", "EUR", name="currencyenum"), nullable=True),
        sa.Column("price_from", sa.Integer(), nullable=True),
        sa.Column("price_to", sa.Integer(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "usersearchfilters",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("search_filter_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("usersearchfilters")
    op.drop_table("searchfilter")
    # ### end Alembic commands ###
